services:
  mysql:
    image: mysql:8
    container_name: mysql-productstore
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productstoredb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/data:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
